controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
api_guesses_create:
    path: /api/guesses
    controller: App\Controller\GuessesController::create
    methods: POST